# Generated by Django 3.0.3 on 2020-02-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='text',
            new_name='price',
        ),
    ]
